// Merit & Exam-Based Scholarships — static dataset
// Source: manually curated for ScholarPath AI

export const MERIT_SCHOLARSHIPS = [
  {
    id: "ntse",
    name: "National Talent Search Examination (NTSE)",
    provider: "NCERT, Govt. of India",
    type: "exam",
    exam_name: "NTSE",
    amount: "₹1,250–₹2,000/month (Class 11–12), ₹2,000/month (UG/PG)",
    amount_numeric: 24000, // annual max for comparison
    coverage: "Up to PhD level",
    eligibility_class: "Class 10 only",
    eligibility_class_key: "10",
    age_limit: "Below 18 years",
    min_marks: "60% in Class 9",
    income_limit: null,
    category: "All categories",
    exam_stages: 2,
    stage1: "State-level (MAT + SAT) — November",
    stage2: "National-level by NCERT — June",
    exam_subjects: ["Mental Ability Test (MAT)", "Scholastic Aptitude Test (SAT) — Maths, Science, Social Science"],
    seats: 2000,
    portal: "https://ncert.nic.in",
    portal_label: "ncert.nic.in",
    reg_window: "Aug – Sep",
    reg_month_start: 8,
    difficulty: "High",
    prepare_guide: {
      overview: "NTSE is one of India's most prestigious school-level scholarships. It has two stages — State (Stage 1) and National (Stage 2). You need to be in Class 10 to apply.",
      timeline: [
        { label: "Register", month: "Aug–Sep", icon: "📝" },
        { label: "Stage 1 Exam", month: "November", icon: "✍️" },
        { label: "Stage 2 Exam", month: "June", icon: "🏆" },
      ],
      tips: [
        "Focus on NCERT textbooks Classes 9 & 10 for SAT (Maths, Science, SST)",
        "Practice previous year MAT papers — pattern recognition and analogy questions are frequent",
        "Stage 1 cutoffs vary by state — check your state's previous year cutoff",
        "Attempt 3–4 mock tests per week in the month before the exam",
        "For Stage 2, difficulty jumps significantly — join a coaching group or study circle",
      ],
    },
  },
  {
    id: "kvpy",
    name: "Kishore Vaigyanik Protsahan Yojana (KVPY)",
    provider: "IISc Bangalore / DST",
    type: "exam",
    exam_name: "KVPY Aptitude Test + Interview",
    amount: "₹5,000–₹7,000/month + ₹20,000–₹28,000 annual contingency",
    amount_numeric: 112000, // annual max (7000×12 + 28000)
    coverage: "Pre-PhD basic science",
    eligibility_class: "Class 11, 12, or 1st year BSc/BS",
    eligibility_class_key: "11-12",
    age_limit: null,
    min_marks: "75% in PCM/PCB (65% for SC/ST)",
    income_limit: null,
    category: "All — purely merit based",
    exam_stages: 2,
    stage1: "Written aptitude test — October/November",
    stage2: "Interview at IISc/IIT centres — Dec–Jan",
    exam_subjects: ["Physics", "Chemistry", "Mathematics", "Biology (optional)"],
    seats: 1250,
    portal: "https://kvpy.iisc.ernet.in",
    portal_label: "kvpy.iisc.ernet.in",
    reg_window: "Jul – Aug",
    reg_month_start: 7,
    difficulty: "Very High",
    prepare_guide: {
      overview: "KVPY selects students passionate about basic sciences. The aptitude test tests conceptual depth — not rote learning. An interview round follows for shortlisted candidates.",
      timeline: [
        { label: "Register", month: "Jul–Aug", icon: "📝" },
        { label: "Aptitude Test", month: "Oct–Nov", icon: "✍️" },
        { label: "Interview", month: "Dec–Jan", icon: "🎤" },
      ],
      tips: [
        "KVPY tests conceptual understanding, not formula application — focus on 'why' not 'what'",
        "Solve HC Verma (Physics) and NCERT exemplars for all science subjects",
        "Previous year KVPY papers are your best resource — solve at least 5 full papers",
        "For the interview: practice explaining concepts in simple language and real-world applications",
        "Biology is optional for SX stream (Class 12) — attempt if you're confident",
        "Time management is critical — don't spend too long on any single question",
      ],
    },
  },
  {
    id: "nmms",
    name: "National Means-cum-Merit Scholarship (NMMS)",
    provider: "Ministry of Education",
    type: "exam",
    exam_name: "NMMS State Exam",
    amount: "₹12,000/year (₹1,000/month)",
    amount_numeric: 12000,
    coverage: "Class 9 to 12",
    eligibility_class: "Class 8 (appearing)",
    eligibility_class_key: "8",
    age_limit: null,
    min_marks: "55% in Class 7 (50% for SC/ST)",
    income_limit: "₹3,50,000/year",
    category: "All — income + merit combined",
    exam_stages: 1,
    stage1: "State-level exam — November (MAT + SAT, 90 Qs each)",
    stage2: null,
    exam_subjects: ["Mental Ability Test (MAT)", "Scholastic Aptitude Test (SAT)"],
    seats: 100000,
    portal: "https://scholarships.gov.in",
    portal_label: "scholarships.gov.in",
    reg_window: "Aug – Sep",
    reg_month_start: 8,
    difficulty: "Moderate",
    prepare_guide: {
      overview: "NMMS is for Class 8 students from economically weaker sections. It's a single state-level exam with MAT and SAT sections (90 questions each). 1 lakh scholarships awarded annually.",
      timeline: [
        { label: "School nominates", month: "Aug–Sep", icon: "🏫" },
        { label: "State Exam", month: "November", icon: "✍️" },
        { label: "Results", month: "Feb–Mar", icon: "🎉" },
      ],
      tips: [
        "Your school nominates you — confirm with your Class 7 teacher that they have registered you",
        "MAT focuses on analogy, classification, pattern-series — practice daily for 20 minutes",
        "SAT covers Class 7 & 8 syllabus in Science, Maths, and Social Science",
        "NCERT Class 7 & 8 textbooks are sufficient — no need for additional material",
        "Solve previous year papers from your state (each state has its own paper)",
      ],
    },
  },
  {
    id: "inspire_she",
    name: "INSPIRE — Scholarship for Higher Education (SHE)",
    provider: "Dept. of Science & Technology",
    type: "merit_marks",
    exam_name: "No exam — top 1% of Class 12 board",
    amount: "₹80,000/year",
    amount_numeric: 80000,
    coverage: "BSc / BS / Int. MSc",
    eligibility_class: "1st year BSc/BS",
    eligibility_class_key: "UG",
    age_limit: null,
    min_marks: "Top 1% of Class 12 board results",
    income_limit: null,
    category: "All — science stream only",
    exam_stages: 0,
    stage1: null,
    stage2: null,
    exam_subjects: [],
    seats: 10000,
    portal: "https://online-inspire.gov.in",
    portal_label: "online-inspire.gov.in",
    reg_window: "Sep – Nov",
    reg_month_start: 9,
    difficulty: "N/A",
    prepare_guide: {
      overview: "INSPIRE SHE requires no separate exam — it is based entirely on your Class 12 board performance. If you scored in the top 1% of your board, you are automatically eligible.",
      timeline: [
        { label: "Class 12 Results", month: "May–Jun", icon: "📊" },
        { label: "Apply Online", month: "Sep–Nov", icon: "📝" },
        { label: "Scholarship credited", month: "Feb–Mar", icon: "💳" },
      ],
      tips: [
        "No separate preparation needed — focus on scoring high in Class 12 boards",
        "Enroll in a BSc/BS programme in Natural/Basic Sciences (Physics, Chemistry, Maths, Biology, etc.)",
        "Apply within the window — late applications are not accepted",
        "Upload all board documents correctly — name must exactly match Aadhaar",
        "Renewal is annual — maintain required academic performance for continuation",
      ],
    },
  },
  {
    id: "css",
    name: "Central Sector Scheme (CSS)",
    provider: "Dept. of Higher Education, MoE",
    type: "merit_marks",
    exam_name: "No exam — top 20 percentile of Class 12 board",
    amount: "₹10,000–₹20,000/year",
    amount_numeric: 20000,
    coverage: "UG and PG",
    eligibility_class: "Post Class 12 / UG students",
    eligibility_class_key: "UG",
    age_limit: null,
    min_marks: "Top 20 percentile of Class 12 board",
    income_limit: "₹4,50,000/year",
    category: "All categories",
    exam_stages: 0,
    stage1: null,
    stage2: null,
    exam_subjects: [],
    seats: null,
    portal: "https://scholarships.gov.in",
    portal_label: "scholarships.gov.in",
    reg_window: "Oct – Nov",
    reg_month_start: 10,
    difficulty: "N/A",
    prepare_guide: {
      overview: "CSS targets meritorious students from lower-income families who are in UG or PG programmes. No separate exam — just board merit + income proof.",
      timeline: [
        { label: "Class 12 Results", month: "May–Jun", icon: "📊" },
        { label: "Apply on NSP", month: "Oct–Nov", icon: "📝" },
        { label: "Disbursement", month: "Mar–Apr", icon: "💳" },
      ],
      tips: [
        "Register on scholarships.gov.in (NSP) — this is the only portal",
        "Family income must be under ₹4.5 lakh per year — obtain income certificate from tehsildar",
        "Your Class 12 percentage must be in the top 20 percentile of your board",
        "Renewal requires 50%+ marks in previous year of study",
        "Check your board's cutoff percentile list published on their official website",
      ],
    },
  },
  {
    id: "reliance_ug",
    name: "Reliance Foundation UG Scholarship",
    provider: "Reliance Foundation",
    type: "exam_plus_interview",
    exam_name: "Online aptitude test + personal interview",
    amount: "Up to ₹2,00,000/year",
    amount_numeric: 200000,
    coverage: "4–5 year UG programs",
    eligibility_class: "1st year UG (STEM, Humanities, Business)",
    eligibility_class_key: "UG",
    age_limit: null,
    min_marks: "60% in Class 12",
    income_limit: "₹6,00,000/year",
    category: "All categories",
    exam_stages: 2,
    stage1: "Online aptitude test",
    stage2: "Personal interview (shortlisted candidates)",
    exam_subjects: ["Quantitative aptitude", "Logical reasoning", "English"],
    seats: 100,
    portal: "https://reliancefoundation.org",
    portal_label: "reliancefoundation.org",
    reg_window: "Jan – Feb",
    reg_month_start: 1,
    difficulty: "Moderate",
    prepare_guide: {
      overview: "Reliance Foundation awards only 100 UG scholarships per year — highly competitive. Selection has two stages: an online aptitude test and a personal interview for shortlisted candidates.",
      timeline: [
        { label: "Apply Online", month: "Jan–Feb", icon: "📝" },
        { label: "Aptitude Test", month: "Mar", icon: "✍️" },
        { label: "Interview", month: "Apr–May", icon: "🎤" },
      ],
      tips: [
        "The aptitude test covers quant, logical reasoning, and English — practice on IndiaBix or aptitide.guru",
        "Write a very specific, personal motivation statement — generic essays are rejected",
        "For the interview: research Reliance Foundation's work and be ready to discuss your career goals",
        "Only 1st year UG students can apply — apply in the very first year",
        "Income certificate (family income under ₹6 lakh) is mandatory — obtain in advance",
      ],
    },
  },
  {
    id: "tata_pankh",
    name: "Tata Capital Pankh Scholarship",
    provider: "Tata Capital Ltd.",
    type: "essay_plus_interview",
    exam_name: "Essay submission + telephonic interview",
    amount: "Up to ₹50,000/year",
    amount_numeric: 50000,
    coverage: "Class 11–12 and UG",
    eligibility_class: "Class 11 to UG 2nd year",
    eligibility_class_key: "11-12",
    age_limit: null,
    min_marks: "60% in last exam",
    income_limit: "₹4,00,000/year",
    category: "All categories",
    exam_stages: 2,
    stage1: "Essay: 'How will this scholarship change your life?'",
    stage2: "Telephonic interview",
    exam_subjects: ["Written essay", "Interview"],
    seats: null,
    portal: "https://buddy4study.com/tata-pankh",
    portal_label: "buddy4study.com/tata-pankh",
    reg_window: "Mar – May",
    reg_month_start: 3,
    difficulty: "Low-Moderate",
    prepare_guide: {
      overview: "Tata Capital Pankh is essay + interview based. The essay prompt is about how the scholarship will change your life — judges look for authenticity, specific plans, and genuine financial need.",
      timeline: [
        { label: "Apply + Essay", month: "Mar–May", icon: "📝" },
        { label: "Shortlisting", month: "Jun", icon: "📋" },
        { label: "Telephonic Interview", month: "Jul–Aug", icon: "📞" },
      ],
      tips: [
        "Write the essay in your own voice — be specific about your goals, not generic aspirations",
        "Mention concrete ways the scholarship will help (fees, books, travel, coaching)",
        "Keep the essay under 400 words and proofread carefully",
        "For the telephonic interview: speak clearly, be honest about your background",
        "Have income documents ready before applying — certificate from block/tehsildar",
        "Apply via Buddy4Study — do not apply directly to Tata Capital",
      ],
    },
  },
];
